// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: firewall/firewall.proto

package firewall

import (
	common "github.com/fishdivinity/BeeCount-Cloud/common/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 防火墙规则请求
type FirewallRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // allow or deny
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_firewall_firewall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_firewall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_firewall_firewall_proto_rawDescGZIP(), []int{0}
}

func (x *FirewallRule) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FirewallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 访问检查请求
type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_firewall_firewall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_firewall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_firewall_firewall_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CheckAccessRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CheckAccessRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// 访问检查响应
type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_firewall_firewall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_firewall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_firewall_firewall_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 删除规则请求
type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_firewall_firewall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_firewall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_firewall_firewall_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRuleRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// 获取规则请求
type GetRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesRequest) Reset() {
	*x = GetRulesRequest{}
	mi := &file_firewall_firewall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRequest) ProtoMessage() {}

func (x *GetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_firewall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRequest.ProtoReflect.Descriptor instead.
func (*GetRulesRequest) Descriptor() ([]byte, []int) {
	return file_firewall_firewall_proto_rawDescGZIP(), []int{4}
}

// 获取规则响应
type GetRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*FirewallRule        `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultAction string                 `protobuf:"bytes,2,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesResponse) Reset() {
	*x = GetRulesResponse{}
	mi := &file_firewall_firewall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesResponse) ProtoMessage() {}

func (x *GetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_firewall_firewall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesResponse.ProtoReflect.Descriptor instead.
func (*GetRulesResponse) Descriptor() ([]byte, []int) {
	return file_firewall_firewall_proto_rawDescGZIP(), []int{5}
}

func (x *GetRulesResponse) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *GetRulesResponse) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

var File_firewall_firewall_proto protoreflect.FileDescriptor

const file_firewall_firewall_proto_rawDesc = "" +
	"\n" +
	"\x17firewall/firewall.proto\x12\bfirewall\x1a\x13common/common.proto\"6\n" +
	"\fFirewallRule\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"V\n" +
	"\x12CheckAccessRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"G\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x11\n" +
	"\x0fGetRulesRequest\"g\n" +
	"\x10GetRulesResponse\x12,\n" +
	"\x05rules\x18\x01 \x03(\v2\x16.firewall.FirewallRuleR\x05rules\x12%\n" +
	"\x0edefault_action\x18\x02 \x01(\tR\rdefaultAction2\x95\x02\n" +
	"\x0fFirewallService\x12J\n" +
	"\vCheckAccess\x12\x1c.firewall.CheckAccessRequest\x1a\x1d.firewall.CheckAccessResponse\x126\n" +
	"\n" +
	"UpdateRule\x12\x16.firewall.FirewallRule\x1a\x10.common.Response\x12;\n" +
	"\n" +
	"DeleteRule\x12\x1b.firewall.DeleteRuleRequest\x1a\x10.common.Response\x12A\n" +
	"\bGetRules\x12\x19.firewall.GetRulesRequest\x1a\x1a.firewall.GetRulesResponseB>Z<github.com/fishdivinity/BeeCount-Cloud/common/proto/firewallb\x06proto3"

var (
	file_firewall_firewall_proto_rawDescOnce sync.Once
	file_firewall_firewall_proto_rawDescData []byte
)

func file_firewall_firewall_proto_rawDescGZIP() []byte {
	file_firewall_firewall_proto_rawDescOnce.Do(func() {
		file_firewall_firewall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_firewall_firewall_proto_rawDesc), len(file_firewall_firewall_proto_rawDesc)))
	})
	return file_firewall_firewall_proto_rawDescData
}

var file_firewall_firewall_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_firewall_firewall_proto_goTypes = []any{
	(*FirewallRule)(nil),        // 0: firewall.FirewallRule
	(*CheckAccessRequest)(nil),  // 1: firewall.CheckAccessRequest
	(*CheckAccessResponse)(nil), // 2: firewall.CheckAccessResponse
	(*DeleteRuleRequest)(nil),   // 3: firewall.DeleteRuleRequest
	(*GetRulesRequest)(nil),     // 4: firewall.GetRulesRequest
	(*GetRulesResponse)(nil),    // 5: firewall.GetRulesResponse
	(*common.Response)(nil),     // 6: common.Response
}
var file_firewall_firewall_proto_depIdxs = []int32{
	0, // 0: firewall.GetRulesResponse.rules:type_name -> firewall.FirewallRule
	1, // 1: firewall.FirewallService.CheckAccess:input_type -> firewall.CheckAccessRequest
	0, // 2: firewall.FirewallService.UpdateRule:input_type -> firewall.FirewallRule
	3, // 3: firewall.FirewallService.DeleteRule:input_type -> firewall.DeleteRuleRequest
	4, // 4: firewall.FirewallService.GetRules:input_type -> firewall.GetRulesRequest
	2, // 5: firewall.FirewallService.CheckAccess:output_type -> firewall.CheckAccessResponse
	6, // 6: firewall.FirewallService.UpdateRule:output_type -> common.Response
	6, // 7: firewall.FirewallService.DeleteRule:output_type -> common.Response
	5, // 8: firewall.FirewallService.GetRules:output_type -> firewall.GetRulesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_firewall_firewall_proto_init() }
func file_firewall_firewall_proto_init() {
	if File_firewall_firewall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_firewall_firewall_proto_rawDesc), len(file_firewall_firewall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_firewall_firewall_proto_goTypes,
		DependencyIndexes: file_firewall_firewall_proto_depIdxs,
		MessageInfos:      file_firewall_firewall_proto_msgTypes,
	}.Build()
	File_firewall_firewall_proto = out.File
	file_firewall_firewall_proto_goTypes = nil
	file_firewall_firewall_proto_depIdxs = nil
}
