// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: business/business.proto

package business

import (
	common "github.com/fishdivinity/BeeCount-Cloud/common/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 账本消息
type Ledger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	mi := &file_business_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{0}
}

func (x *Ledger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ledger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ledger) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ledger) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Ledger) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Ledger) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ledger) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// 交易消息
type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LedgerId        string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // income, expense, transfer
	CategoryId      string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SubcategoryId   string                 `protobuf:"bytes,6,opt,name=subcategory_id,json=subcategoryId,proto3" json:"subcategory_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,7,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	TargetAccountId string                 `protobuf:"bytes,8,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	Amount          string                 `protobuf:"bytes,9,opt,name=amount,proto3" json:"amount,omitempty"` // 使用字符串避免精度问题
	Description     string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Date            string                 `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Tags            map[string]string      `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_business_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Transaction) GetSubcategoryId() string {
	if x != nil {
		return x.SubcategoryId
	}
	return ""
}

func (x *Transaction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Transaction) GetTargetAccountId() string {
	if x != nil {
		return x.TargetAccountId
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Transaction) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 同步请求
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSyncTime  int64                  `protobuf:"varint,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Ledgers       []*Ledger              `protobuf:"bytes,5,rep,name=ledgers,proto3" json:"ledgers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_business_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *SyncRequest) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SyncRequest) GetLedgers() []*Ledger {
	if x != nil {
		return x.Ledgers
	}
	return nil
}

// 同步响应
type SyncResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SyncTime              int64                  `protobuf:"varint,1,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	Transactions          []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Ledgers               []*Ledger              `protobuf:"bytes,3,rep,name=ledgers,proto3" json:"ledgers,omitempty"`
	DeletedTransactionIds []string               `protobuf:"bytes,4,rep,name=deleted_transaction_ids,json=deletedTransactionIds,proto3" json:"deleted_transaction_ids,omitempty"`
	DeletedLedgerIds      []string               `protobuf:"bytes,5,rep,name=deleted_ledger_ids,json=deletedLedgerIds,proto3" json:"deleted_ledger_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_business_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetSyncTime() int64 {
	if x != nil {
		return x.SyncTime
	}
	return 0
}

func (x *SyncResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *SyncResponse) GetLedgers() []*Ledger {
	if x != nil {
		return x.Ledgers
	}
	return nil
}

func (x *SyncResponse) GetDeletedTransactionIds() []string {
	if x != nil {
		return x.DeletedTransactionIds
	}
	return nil
}

func (x *SyncResponse) GetDeletedLedgerIds() []string {
	if x != nil {
		return x.DeletedLedgerIds
	}
	return nil
}

// 获取账本列表请求
type GetLedgersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgersRequest) Reset() {
	*x = GetLedgersRequest{}
	mi := &file_business_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgersRequest) ProtoMessage() {}

func (x *GetLedgersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgersRequest.ProtoReflect.Descriptor instead.
func (*GetLedgersRequest) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{4}
}

func (x *GetLedgersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLedgersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLedgersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取账本列表响应
type GetLedgersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ledgers       []*Ledger              `protobuf:"bytes,1,rep,name=ledgers,proto3" json:"ledgers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgersResponse) Reset() {
	*x = GetLedgersResponse{}
	mi := &file_business_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgersResponse) ProtoMessage() {}

func (x *GetLedgersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgersResponse.ProtoReflect.Descriptor instead.
func (*GetLedgersResponse) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{5}
}

func (x *GetLedgersResponse) GetLedgers() []*Ledger {
	if x != nil {
		return x.Ledgers
	}
	return nil
}

func (x *GetLedgersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetLedgersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLedgersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_business_business_proto protoreflect.FileDescriptor

const file_business_business_proto_rawDesc = "" +
	"\n" +
	"\x17business/business.proto\x12\bbeecount\x1a\x13common/common.proto\"\xc1\x01\n" +
	"\x06Ledger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xf4\x03\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12%\n" +
	"\x0esubcategory_id\x18\x06 \x01(\tR\rsubcategoryId\x12\x1d\n" +
	"\n" +
	"account_id\x18\a \x01(\tR\taccountId\x12*\n" +
	"\x11target_account_id\x18\b \x01(\tR\x0ftargetAccountId\x12\x16\n" +
	"\x06amount\x18\t \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x12\n" +
	"\x04date\x18\v \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x123\n" +
	"\x04tags\x18\x0e \x03(\v2\x1f.beecount.Transaction.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\vSyncRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12$\n" +
	"\x0elast_sync_time\x18\x03 \x01(\x03R\flastSyncTime\x129\n" +
	"\ftransactions\x18\x04 \x03(\v2\x15.beecount.TransactionR\ftransactions\x12*\n" +
	"\aledgers\x18\x05 \x03(\v2\x10.beecount.LedgerR\aledgers\"\xf8\x01\n" +
	"\fSyncResponse\x12\x1b\n" +
	"\tsync_time\x18\x01 \x01(\x03R\bsyncTime\x129\n" +
	"\ftransactions\x18\x02 \x03(\v2\x15.beecount.TransactionR\ftransactions\x12*\n" +
	"\aledgers\x18\x03 \x03(\v2\x10.beecount.LedgerR\aledgers\x126\n" +
	"\x17deleted_transaction_ids\x18\x04 \x03(\tR\x15deletedTransactionIds\x12,\n" +
	"\x12deleted_ledger_ids\x18\x05 \x03(\tR\x10deletedLedgerIds\"]\n" +
	"\x11GetLedgersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x87\x01\n" +
	"\x12GetLedgersResponse\x12*\n" +
	"\aledgers\x18\x01 \x03(\v2\x10.beecount.LedgerR\aledgers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xf1\x03\n" +
	"\x0fBusinessService\x125\n" +
	"\x04Sync\x12\x15.beecount.SyncRequest\x1a\x16.beecount.SyncResponse\x12G\n" +
	"\n" +
	"GetLedgers\x12\x1b.beecount.GetLedgersRequest\x1a\x1c.beecount.GetLedgersResponse\x122\n" +
	"\fCreateLedger\x12\x10.beecount.Ledger\x1a\x10.beecount.Ledger\x122\n" +
	"\fUpdateLedger\x12\x10.beecount.Ledger\x1a\x10.beecount.Ledger\x122\n" +
	"\fDeleteLedger\x12\x10.beecount.Ledger\x1a\x10.common.Response\x12A\n" +
	"\x11CreateTransaction\x12\x15.beecount.Transaction\x1a\x15.beecount.Transaction\x12A\n" +
	"\x11UpdateTransaction\x12\x15.beecount.Transaction\x1a\x15.beecount.Transaction\x12<\n" +
	"\x11DeleteTransaction\x12\x15.beecount.Transaction\x1a\x10.common.ResponseB>Z<github.com/fishdivinity/BeeCount-Cloud/common/proto/businessb\x06proto3"

var (
	file_business_business_proto_rawDescOnce sync.Once
	file_business_business_proto_rawDescData []byte
)

func file_business_business_proto_rawDescGZIP() []byte {
	file_business_business_proto_rawDescOnce.Do(func() {
		file_business_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_business_proto_rawDesc), len(file_business_business_proto_rawDesc)))
	})
	return file_business_business_proto_rawDescData
}

var file_business_business_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_business_business_proto_goTypes = []any{
	(*Ledger)(nil),             // 0: beecount.Ledger
	(*Transaction)(nil),        // 1: beecount.Transaction
	(*SyncRequest)(nil),        // 2: beecount.SyncRequest
	(*SyncResponse)(nil),       // 3: beecount.SyncResponse
	(*GetLedgersRequest)(nil),  // 4: beecount.GetLedgersRequest
	(*GetLedgersResponse)(nil), // 5: beecount.GetLedgersResponse
	nil,                        // 6: beecount.Transaction.TagsEntry
	(*common.Response)(nil),    // 7: common.Response
}
var file_business_business_proto_depIdxs = []int32{
	6,  // 0: beecount.Transaction.tags:type_name -> beecount.Transaction.TagsEntry
	1,  // 1: beecount.SyncRequest.transactions:type_name -> beecount.Transaction
	0,  // 2: beecount.SyncRequest.ledgers:type_name -> beecount.Ledger
	1,  // 3: beecount.SyncResponse.transactions:type_name -> beecount.Transaction
	0,  // 4: beecount.SyncResponse.ledgers:type_name -> beecount.Ledger
	0,  // 5: beecount.GetLedgersResponse.ledgers:type_name -> beecount.Ledger
	2,  // 6: beecount.BusinessService.Sync:input_type -> beecount.SyncRequest
	4,  // 7: beecount.BusinessService.GetLedgers:input_type -> beecount.GetLedgersRequest
	0,  // 8: beecount.BusinessService.CreateLedger:input_type -> beecount.Ledger
	0,  // 9: beecount.BusinessService.UpdateLedger:input_type -> beecount.Ledger
	0,  // 10: beecount.BusinessService.DeleteLedger:input_type -> beecount.Ledger
	1,  // 11: beecount.BusinessService.CreateTransaction:input_type -> beecount.Transaction
	1,  // 12: beecount.BusinessService.UpdateTransaction:input_type -> beecount.Transaction
	1,  // 13: beecount.BusinessService.DeleteTransaction:input_type -> beecount.Transaction
	3,  // 14: beecount.BusinessService.Sync:output_type -> beecount.SyncResponse
	5,  // 15: beecount.BusinessService.GetLedgers:output_type -> beecount.GetLedgersResponse
	0,  // 16: beecount.BusinessService.CreateLedger:output_type -> beecount.Ledger
	0,  // 17: beecount.BusinessService.UpdateLedger:output_type -> beecount.Ledger
	7,  // 18: beecount.BusinessService.DeleteLedger:output_type -> common.Response
	1,  // 19: beecount.BusinessService.CreateTransaction:output_type -> beecount.Transaction
	1,  // 20: beecount.BusinessService.UpdateTransaction:output_type -> beecount.Transaction
	7,  // 21: beecount.BusinessService.DeleteTransaction:output_type -> common.Response
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_business_business_proto_init() }
func file_business_business_proto_init() {
	if File_business_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_business_proto_rawDesc), len(file_business_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_business_proto_goTypes,
		DependencyIndexes: file_business_business_proto_depIdxs,
		MessageInfos:      file_business_business_proto_msgTypes,
	}.Build()
	File_business_business_proto = out.File
	file_business_business_proto_goTypes = nil
	file_business_business_proto_depIdxs = nil
}
